version: "3.7"


services:

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    networks:
      - django
    volumes:
      - /home/jwh4861230/nginx.conf:/etc/nginx/nginx.conf
      - cat_static:/data/static/
      - cat_media:/data/media/


  django:
    image: cat_django:4
    networks:
      - django
    volumes :
      - cat_media:/home/MYPROJECT/media
      - cat_static:/home/MYPROJECT/static

  mariadb:
    image: mariadb:10.5
    networks:
      - django
    volumes:
    - cat_mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: django
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: django

networks:
  django:

volumes:
  cat_static:
  cat_media:
  cat_mariadb: